name: "Icecast Server"
version: "1.0.3"
slug: "icecast"
description: "Self-host your own Icecast streaming server inside Home Assistant"
startup: services
boot: auto
hassio_api: false
homeassistant_api: false
host_network: true
ingress: false
panel_icon: mdi:radio
panel_title: "Icecast"
log_level: info

arch:
  - amd64
  - aarch64
  - armv7

ports:
  "{{ options.port }}/tcp": "{{ options.port }}"
ports_description:
  "{{ options.port }}/tcp": "Icecast server port for streaming and administration"

options:
  source_password: "hackme"
  admin_password: "adminhack"
  relay_password: "relayhack"
  max_clients: 100
  port: 8000

schema:
  source_password: password
  admin_password: password
  relay_password: password
  max_clients: int
  port: int
